import { THEMES } from '../config/uiConfig';
import { filesApi } from '../services/apiClient';
import { OCTOPUS_ABOUT_MESSAGE } from '../utils/chatMessages';

export function useTitleMenuItems({
  activeFile,
  activateRightPanel,
  activateSidebarPanel,
  clearSearch,
  closeActiveFile,
  closeAllFiles,
  commitMsg,
  copyCurrentFilePath,
  createScratchFile,
  currentDir,
  currentFile,
  doCommit,
  files,
  gitFiles,
  installedExtensions,
  isRunning,
  loadGitStatus,
  openFolder,
  openProjectFileByName,
  openTerminalTab,
  refreshFileTree,
  reset,
  resetLayout,
  restartProject,
  rightPanelOpen,
  saveAllOpenFiles,
  saveCurrentFile,
  searchInputRef,
  searchQuery,
  searchResults,
  setMessages,
  setRightPanelOpen,
  setSidebarOpen,
  setTerminalOpen,
  setTheme,
  sidebarOpen,
  terminalOpen,
  theme,
  toggleRun,
}) {
  const showStatusSummary = () => {
    setMessages(prev => [...prev, {
      role: 'octopus',
      text: `Status: ${files.length} open file(s), ${gitFiles.length} git item(s), ${installedExtensions.length} extension(s).`,
    }]);
  };

  return [
    {
      id: 'file', label: 'File',
      items: [
        { label: 'Open Folder...', icon: 'codicon-folder-opened', action: () => openFolder(), shortcut: 'Ctrl+O' },
        { label: 'New File', icon: 'codicon-new-file', action: createScratchFile, shortcut: 'Ctrl+N' },
        { separator: true },
        { label: 'Save', icon: 'codicon-save', action: saveCurrentFile, shortcut: 'Ctrl+S', disabled: !currentFile?.path },
        { label: 'Save All', icon: 'codicon-save-all', action: saveAllOpenFiles, shortcut: 'Ctrl+K S', disabled: !files.some(file => file.path && file.content !== undefined) },
        { separator: true },
        { label: 'Close File', icon: 'codicon-close', action: closeActiveFile, shortcut: 'Ctrl+W', disabled: !activeFile },
        { label: 'Close All Files', icon: 'codicon-close-all', action: closeAllFiles, disabled: files.length === 0 },
        { separator: true },
        { label: 'Refresh Explorer', icon: 'codicon-refresh', action: refreshFileTree, disabled: !currentDir },
        { separator: true },
        { label: 'Reset Conversation', icon: 'codicon-refresh', action: () => reset() },
      ],
    },
    {
      id: 'edit', label: 'Edit',
      items: [
        { label: 'Search in Files', icon: 'codicon-search', action: () => activateSidebarPanel('search'), shortcut: 'Ctrl+Shift+F' },
        { label: 'Focus Quick Search', icon: 'codicon-search-fuzzy', action: () => { searchInputRef.current?.focus(); searchInputRef.current?.select(); }, shortcut: 'Ctrl+P' },
        { label: 'Clear Search', icon: 'codicon-clear-all', action: clearSearch, disabled: !searchQuery && searchResults.length === 0 },
        { separator: true },
        { label: 'Copy Current Path', icon: 'codicon-copy', action: copyCurrentFilePath, disabled: !activeFile && !currentFile?.path },
        { label: 'Open Current in Explorer', icon: 'codicon-go-to-file', action: () => currentFile?.path && filesApi.showInExplorer(currentFile.path), disabled: !currentFile?.path },
        { separator: true },
        { label: 'File Explorer', icon: 'codicon-files', action: () => activateSidebarPanel('explorer'), shortcut: 'Ctrl+Shift+E' },
        { label: 'Git', icon: 'codicon-source-control', action: () => activateSidebarPanel('git'), shortcut: 'Ctrl+Shift+G' },
      ],
    },
    {
      id: 'view', label: 'View',
      items: [
        { label: sidebarOpen ? 'Hide Sidebar' : 'Show Sidebar', icon: 'codicon-layout-sidebar-left', action: () => setSidebarOpen(p => !p), shortcut: 'Ctrl+B' },
        { label: terminalOpen ? 'Hide Terminal' : 'Show Terminal', icon: 'codicon-terminal', action: () => setTerminalOpen(p => !p), shortcut: 'Ctrl+`' },
        { label: rightPanelOpen ? 'Hide Chat Panel' : 'Show Chat Panel', icon: 'codicon-comment-discussion', action: () => setRightPanelOpen(p => !p) },
        { separator: true },
        { label: 'Explorer', icon: 'codicon-files', action: () => activateSidebarPanel('explorer') },
        { label: 'Search', icon: 'codicon-search', action: () => activateSidebarPanel('search') },
        { label: 'Source Control', icon: 'codicon-source-control', action: () => activateSidebarPanel('git') },
        { label: 'Extensions', icon: 'codicon-extensions', action: () => activateSidebarPanel('extensions') },
        { separator: true },
        { label: 'Chat', icon: 'codicon-comment-discussion', action: () => activateRightPanel('chat') },
        { label: 'Eight Legs', icon: 'codicon-pulse', action: () => activateRightPanel('legs') },
        { label: 'Live Timeline', icon: 'codicon-list-ordered', action: () => activateRightPanel('timeline') },
        { label: 'Runtime Inspector', icon: 'codicon-debug-alt', action: () => activateRightPanel('inspector') },
        { label: 'Context', icon: 'codicon-list-tree', action: () => activateRightPanel('context') },
        { label: 'History', icon: 'codicon-history', action: () => activateRightPanel('history') },
        { separator: true },
        { label: 'Reset Layout', icon: 'codicon-layout', action: resetLayout },
        { separator: true },
        ...Object.entries(THEMES).map(([key, th]) => ({
          label: th.name,
          icon: theme === key ? 'codicon-check' : 'codicon-circle-large-outline',
          action: () => setTheme(key),
        })),
      ],
    },
    {
      id: 'run', label: 'Run',
      items: [
        { label: isRunning ? 'Stop Project' : 'Run Project', icon: isRunning ? 'codicon-debug-stop' : 'codicon-play', action: () => { toggleRun(); }, shortcut: 'F5' },
        { label: 'Restart Project', icon: 'codicon-debug-restart', action: restartProject, disabled: !currentDir },
        { separator: true },
        { label: 'Open Terminal', icon: 'codicon-terminal', action: () => openTerminalTab('terminal') },
        { label: 'Show Problems', icon: 'codicon-warning', action: () => openTerminalTab('problems') },
        { label: 'Show Output', icon: 'codicon-output', action: () => openTerminalTab('output') },
        { separator: true },
        { label: 'Refresh Git Status', icon: 'codicon-sync', action: loadGitStatus, disabled: !currentDir },
        { label: 'Commit Changes', icon: 'codicon-check', action: doCommit, disabled: !commitMsg.trim() || gitFiles.length === 0 },
      ],
    },
    {
      id: 'help', label: 'Help',
      items: [
        { label: 'About Octopus', icon: 'codicon-info', action: () => setMessages(prev => [...prev, OCTOPUS_ABOUT_MESSAGE]) },
        { label: 'Project Status', icon: 'codicon-dashboard', action: showStatusSummary },
        { separator: true },
        { label: 'Extensions', icon: 'codicon-extensions', action: () => activateSidebarPanel('extensions') },
        { label: 'Open Report', icon: 'codicon-book', action: () => openProjectFileByName('REPORT.md') },
        { label: 'Open TODO', icon: 'codicon-checklist', action: () => openProjectFileByName('TODO.md') },
      ],
    },
  ];
}
